-- T8: extend RelationType enum with 12 new values (one ADD VALUE per statement;
-- IF NOT EXISTS makes the migration re-runnable). Existing 5 values kept for compat.

ALTER TYPE "RelationType" ADD VALUE IF NOT EXISTS 'CONTAINS';
ALTER TYPE "RelationType" ADD VALUE IF NOT EXISTS 'COMPOSED_OF';
ALTER TYPE "RelationType" ADD VALUE IF NOT EXISTS 'ATTACHED_TO';
ALTER TYPE "RelationType" ADD VALUE IF NOT EXISTS 'CONNECTS_TO';
ALTER TYPE "RelationType" ADD VALUE IF NOT EXISTS 'UPLINKS_TO';
ALTER TYPE "RelationType" ADD VALUE IF NOT EXISTS 'REPLICATES_TO';
ALTER TYPE "RelationType" ADD VALUE IF NOT EXISTS 'POWERS';
ALTER TYPE "RelationType" ADD VALUE IF NOT EXISTS 'PROTECTS';
ALTER TYPE "RelationType" ADD VALUE IF NOT EXISTS 'RUNS_ON';
ALTER TYPE "RelationType" ADD VALUE IF NOT EXISTS 'QUERIES';
ALTER TYPE "RelationType" ADD VALUE IF NOT EXISTS 'LICENSES';
ALTER TYPE "RelationType" ADD VALUE IF NOT EXISTS 'MANAGES';
